hjk0761/Almumol

ikjo39/README.md
=> [1주차 1회차] 다온

jminkkk/241216.md
=> [1주차 1회차] 몰리

hyxrxn/28353.cpp, hyxrxn/32248.cpp
- 28353 고양이 카페 (실버3)
- 32248 더 게임 오브 데스 (실버1)
=> [1주차 1회차] 아토

slimsha2dy/23978.cpp
조금 늦었네요 ㅎㅎ 갑자기 에디터 deprecated 문제가 터져서 그만..
전 골드 한 문제 풀었습니다!
=> [1주차 1회차] 알파카

ikjo39/1217/P_19637.java, ikjo39/1217/P_24499.java, ikjo39/README.md
=> [1주차 2회차] 다온

nak-honest/Baekjoon/GOLD/팀_배정(18768).py
https://www.acmicpc.net/problem/18768
=> [1주차 2회차] 낙낙

slimsha2dy/10211.cpp, slimsha2dy/11060.cpp
=> [1주차 2회차] 알파카

nak-honest/Baekjoon/GOLD/개미굴(14725).py
https://www.acmicpc.net/problem/14725
=> [1주차 3회차] 낙낙

ikjo39/1217/P_25916.java, ikjo39/1217/P_27376.java, ikjo39/README.md
=> [1주차 3회차] 다온

nak-honest/Baekjoon/GOLD/너_봄에는_캡사이신이_맛있단다(15824).py
https://www.acmicpc.net/problem/15824
꾸준하게 푸니 좋네요 ㅎㅎ
=> [1주차 4회차] 낙낙

hyxrxn/27514.cpp, hyxrxn/31848.cpp
- 27514 1차원 2048 (실버3)
- 31848 엉성한 도토리 분류기 (실버2)
=> [1주차 2회차] 아토

hyxrxn/15703.cpp
=> [1주차 3회차] 아토

nak-honest/Baekjoon/GOLD/N포커(16565).py
https://www.acmicpc.net/problem/16565
=> [1주차 5회차] 낙낙

robinjoon/1week/day2/Programers147355.kts, robinjoon/1week/day2/Programers42746.kts, robinjoon/1week/day2/Programers42747.kts
- https://school.programmers.co.kr/learn/courses/30/lessons/42747?language=kotlin
- https://school.programmers.co.kr/learn/courses/30/lessons/42746?language=kotlin
- https://school.programmers.co.kr/learn/courses/30/lessons/147355?language=kotlin
코틀린에서는 타입을 상속하지 않고 기능을 추가할 수 있습니다. 이를 코틀린 문서에선 extensions 라고 부르고, 한국어론 확장 함수, 확장 프로퍼티라 부릅니다. 클래스의 상속이 막혀있거나, 특정 클래스 내에서 임시로 기능을 추가하는 경우 유용하게 사용할 수 있습니다. 또한, 라이브러리를 만드는 경우 사용할 수 있고, 실제로 많은 라이브러리들이 확장 함수 기능을 고도로 이용하고 있습니다.
```kotlin
fun String.findAllSubStrings(length: Int): List<String> = // 확장 함수 정의.
(0..this.lastIndex - length + 1)
.map { this.substring(it, it + length) }
.toList()
class Solution {
fun solution(t: String, p: String): Int {
return t.findAllSubStrings(p.length).map { // 확장 함수 사용
it.toLong()
}.count { it <= p.toLong() }
}
}
``` …
=> 1주차 2회차 로빈

jminkkk/241221.md, jminkkk/241222.md
=> [1주차 4회차] 몰리

jminkkk/241222.md
=> [1주차 5회차] 몰리

ikjo39/README.md, ikjo39/week2/P_16401.java, ikjo39/week2/P_17264.java
=> [2주차 1회차] 다온

nak-honest/Baekjoon/GOLD/보물_찾기_2(27978).py, nak-honest/Baekjoon/GOLD/철로(13334).py
어제 풀다 만거라 오늘 2개 올리도록 하겠습니다!!
https://www.acmicpc.net/problem/27978
=> [2주차 1회차] 낙낙

jminkkk/241224.md
=> [2주차 2회차] 몰리

jminkkk/241225.md
레벨2 한문제 풀었어요~!
레벨2라 실버라고 생각하고 이번주는 6회차까지 하겠습니다~~
=> [2주차 3회차] 몰리

slimsha2dy/11404.cpp
=> [2주차 1회차] 알파카

nak-honest/Baekjoon/GOLD/구간_합_구하기(2042).py
https://www.acmicpc.net/problem/2042
python3는 시간초과 나고, pypy3 로만 통과되긴 합니닷 ㅎ,,
정석 풀이는 세그먼트 트리라길래 호다닥 도망치겠습니다
=> [2주차 3회차] 낙낙

jminkkk/241226.md
=> [2주차 4회차] 몰리

nak-honest/Baekjoon/GOLD/꼬인_전깃줄(1365).py
https://www.acmicpc.net/problem/1365
=> [2주차 4회차] 낙낙

nak-honest/Baekjoon/GOLD/킥보드로_등교하기(27977).py
https://www.acmicpc.net/problem/27977
=> [2주차 5회차] 낙낙

slimsha2dy/2467.cpp
=> [2주차 2회차] 알파카

hyxrxn/09252.cpp
- 9252 LCS 2 (골드4)
앞 부분은 어제꺼 안보고... 새로 풀어보았답니다...~~!!
=> [2주차 2회차] 아토

nak-honest/Baekjoon/GOLD/나는_북극곰입니다(31932).py
https://www.acmicpc.net/problem/31932
=> [3주차 1회차] 낙낙

ikjo39/README.md, ikjo39/week3/P_29808.java, ikjo39/week3/P_30645.java
=> [3주차 1회차] 다온

slimsha2dy/10942.cpp
=> [3주차 1회차] 알파카

nak-honest/Baekjoon/GOLD/수열과_쿼리_15(14427).py
https://www.acmicpc.net/problem/14427
오늘 폭포가 추천해 준 문제입니닷!!
=> [3주차 2회차] 낙낙

hyxrxn/02805.cpp, hyxrxn/20300.cpp
- 2805 나무 자르기 (실버 2)
- 20300 서강근육맨 (실버 3)
=> [3주차 1회차] 아토

nak-honest/Baekjoon/GOLD/해킹(10282).py
https://www.acmicpc.net/problem/10282
플레 문제 도전했는데 너무 어렵네요 ㅠㅠ
바로 골드 문제로 눈 낮췄슴다 ㅎㅋ
=> [3주차 3회차] 낙낙

slimsha2dy/9252.cpp
=> [3주차 3회차] 알파카

nak-honest/Baekjoon/GOLD/소형기관차(2616).py
https://www.acmicpc.net/problem/2616
스터디 덕에 꾸준히 푸니 좋네요!
재밌는 dp 문제였슴다
=> [3주차 5회차] 낙낙

hyxrxn/15828.cpp, hyxrxn/15903.cpp
- 15828 Router (실버 4)
- 15903 카드 합체 놀이 (실버 1)
=> [3주차 2회차] 아토

jminkkk/250104.md, jminkkk/250105.md
+) 어제 올린 게 머지가 안돼서 5일이랑 PR이 하나입니다~
=> [3주차 3회차, 4회차] 몰리

hyxrxn/17298.cpp
=> [4주차 1회차] 아토

fromitive/find-the-highest-altitude.py, fromitive/k-radius-subarray-averages.py, fromitive/minimum-size-subarray-sum.py, fromitive/reverse-only-letters.py, fromitive/reverse-words-in-a-string-iii.py
ㅎㅇㅎㅇ 투 포인터, 슬라이딩 윈도우, 프리픽스 문제 마무리 합니당.
=> [4주차 3회차] 포케

ikjo39/README.md, ikjo39/week4/P_11726.java, ikjo39/week4/P_27375.java
=> [4주차 1회차] 다온

shin-jisong/week1/day1/boj11050.py, shin-jisong/week1/day1/boj1546.py, shin-jisong/week1/day1/boj1773.py, shin-jisong/week1/day1/boj2609.py
=> [4주차 1회차] 시소

ikjo39/README.md, ikjo39/week4/P_29754.java, ikjo39/week4/P_30701.java
=> [4주차 2회차] 다온

hyxrxn/01012.cpp, hyxrxn/01991.cpp
- 1012 유기농 배추 (실버 2)
- 1991 트리 순회 (실버 1)
=> [4주차 2회차] 아토

slimsha2dy/15681.cpp
=> [4주차 2회차] 알파카

slimsha2dy/15681.cpp, slimsha2dy/1647.cpp
=> [4주차 4회차] 알파카

ikjo39/README.md, ikjo39/week4/P_14940.java, ikjo39/week4/P_30804.java
=> [4주차 3회차] 다온

nak-honest/Baekjoon/GOLD/발전소_설치(1277).py
https://www.acmicpc.net/problem/1277
오랜만에 뵙는군요!
저번 한주는 동아리 활동을 다녀와서 못했습니다 ㅎㅎ
오늘부터 다시 열심히 하겠슴다!
=> [5주차 1회차] 낙낙

nak-honest/Baekjoon/GOLD/호텔(1106).py
https://www.acmicpc.net/problem/1106
=> [5주차 2회차] 낙낙

ikjo39/README.md, ikjo39/week5/P_2447.java
=> [5주차 1회차] 다온

slimsha2dy/2252.cpp
열심히 고민했는데 모르는 개념이었네요.. 위상정렬 처음 풀어보고 가요~
=> [5주차 2회차] 알파카

hyxrxn/13422.cpp
=> [5주차 1회차] 아토

ikjo39/README.md, ikjo39/week5/P_1759.java
=> [5주차 2회차] 다온

youngsu5582/week1/BJ_13549.java
https://www.acmicpc.net/problem/13549
질문 보다가 DP 로도 된다고 해서 생각하다가
한참 헤맸내여; 글고 DP 가 맞는지도 의문 🥲
=> [5주차 1회차] 조이썬

nak-honest/Baekjoon/PLATINUM/찾기(1786).py
https://www.acmicpc.net/problem/1786
=> [5주차 3회차] 낙낙

youngsu5582/week1/BJ_10211.kt, youngsu5582/week1/BJ_13549.java, youngsu5582/week1/BJ_29808.kt, youngsu5582/week1/BJ_30702.java
실버는 코틀린으로 풀어도 되겠지 생각했는데
생각보다 코틀린이 어렵네요 🥲
=>  [5주차 2회차] 조이썬

nak-honest/Baekjoon/GOLD/할_일_정하기_1(1311).py
https://www.acmicpc.net/problem/1311
DP + 비트마스킹은 역시 어렵군요..
=> [5주차 5회차] 낙낙

fromitive/longest-continuous-subarray-with-absolute-diff-less-than-or-equal-to-limit.py, fromitive/max-sliding-window.py, fromitive/next-greater-element-i.py, fromitive/next-greater-element-ii.py
=> [5주차 4회차] 포케

youngsu5582/week1/BJ_2193.kt, youngsu5582/week1/BJ_2668.kt
하나 골드긴 한디, 레벨5라 실버라 생각하고 2개 풀었습니다.
=> [5주차 3회차] 조이썬

hyxrxn/01629.cpp, hyxrxn/02630.cpp
- 2630 색종이 만들기 (실버 2)
- 1629 곱셈 (실버 1)
=> [5주차 2회차] 아토

youngsu5582/week2/BJ_12933.kt, youngsu5582/week2/BJ_2232.kt, youngsu5582/week2/BJ_5619.kt
실버 문제가 딱 재밌고, 생각으로 풀리는디...
골드 풀기 싫어요 😭
- 문제 링크
https://www.acmicpc.net/problem/12933
https://www.acmicpc.net/problem/2232
https://www.acmicpc.net/problem/5619
=> [6주차 1회차] 조이썬

slimsha2dy/11723.cpp, slimsha2dy/14940.cpp
=> [5주차 4회차] 알파카

nak-honest/Baekjoon/GOLD/겹치는_선분(1689).py
https://www.acmicpc.net/problem/1689
라이브 코딩에서 나온 문제와 완전히 같은 문제인데 라코 땐 좀 많이 헤맸습니다 ㅠㅠ
스위핑, 그리디 유형이던데 둘다 익숙치 않은 유형이라 연습 좀 해야겠슴다 ㅎㅎ
=> [6주차 3회차] 낙낙

fromitive/closest-binary-search-tree-value.py, fromitive/contiguous-array.py, fromitive/find-if-path-exists-in-graph.py, fromitive/keys-and-rooms.py, fromitive/max-area-of-island.py, fromitive/minimum-number-of-vertices-to-reach-all-nodes.py, fromitive/number-of-connected-components-in-an-undirected-graph.py, fromitive/remove-all-adjacent-duplicates-in-string.py
=> [6주차 4회차] 포케

nak-honest/Baekjoon/GOLD/행복_유치원(13164).py
https://www.acmicpc.net/problem/13164
=> [6주차 4회차] 낙낙

fromitive/moving-average-from-data-stream.py, fromitive/reachable-nodes-with-restrictions.py, fromitive/shortest-path-in-binary-matrix.py, fromitive/sliding-window-maximum.py
=> [6주차 5회차] 포케

hyxrxn/java/6278.java
=> [6주차 2회차] 아토

nak-honest/Baekjoon/GOLD/허들_넘기(23286).py
https://www.acmicpc.net/problem/23286
=> [6주차 5회차] 낙낙

slimsha2dy/11779.cpp
=> [6주차 4회차] 알파카

youngsu5582/week2/BJ_16401.kt, youngsu5582/week2/BJ_23830.kt, youngsu5582/week2/BJ_31785.kt
- 문제 링크 : https://www.acmicpc.net/problem/23830 ( 이분탐색 )
- 문제 링크 : https://www.acmicpc.net/problem/16401 ( 이분탐색 ) 
- 문제 링크 : https://www.acmicpc.net/problem/31785 ( 슬라이딩 윈도우 )
=> [6주차 3회차] 조이썬

slimsha2dy/1753.cpp
=> [6주차 3회차] 알파카

nak-honest/Baekjoon/GOLD/감시(15683).py
https://www.acmicpc.net/problem/15683
=> [6.5주차 2회차] 낙낙

nak-honest/Baekjoon/GOLD/연구소_3(17142).py
https://www.acmicpc.net/problem/17142
=> [6.5주차 3회차] 낙낙

youngsu5582/week3/BJ_11404.kt, youngsu5582/week3/BJ_23352.kt
- 문제 링크 : https://www.acmicpc.net/problem/23352
BFS 인건 파악했는데
왜 시작하는 좌표를 `visited=true` 를 해야하는지는 아직도 의문이네용 🥲
`시작 방과 끝 방은 동일한 위치일 수도 있다.` 해당 조건 때문에 처음을 false 로 하니 실패떴습니당
=> [6.5주차 2회차] 조이썬

nak-honest/Baekjoon/GOLD/탑_보기(22866).py
https://www.acmicpc.net/problem/22866
=> [6.5주차] 4주차 낙낙

nak-honest/Baekjoon/GOLD/가희와_탑(24337).py
https://www.acmicpc.net/problem/24337
규칙 찾는게 재밌는 문제네욥 ㅎㅎ
=> [6.5주차 5회차] 낙낙

nak-honest/Baekjoon/PLATINUM/거의_최단_경로(5719).py
https://www.acmicpc.net/problem/5719
최단 경로 알고리즘의 원리만 안다면 풀 수 있어욥!!
문제 추천합니닷!
=> [7주차 1회차] 낙낙

youngsu5582/week4/BJ_2156.kt, youngsu5582/week4/BJ_2470.kt
- 문제 링크 : https://www.acmicpc.net/problem/2156
- 문제 링크 : https://www.acmicpc.net/problem/2470
DP 너무 싫어요...
이중 포인터 문제는 범위 때매 헤매고 그냥 쉬웠던 거 같아용
=> [7주차 1회차] 조이썬

fromitive/boats-to-save-people.py, fromitive/destroying-asteroids.py, fromitive/find-k-closest-elements.py, fromitive/how-many-apples-can-you-put-into-the-basket.py, fromitive/ipo.py, fromitive/k-closest-points-to-origin.py, fromitive/kth-largest-element-in-a-stream.py, fromitive/kth-largest-element-in-an-array.py, fromitive/least-number-of-unique-integers-after-k-removals.py, fromitive/maximum-69-number.py, fromitive/maximum-ascending-subarray-sum.py, fromitive/maximum-units-on-a-truck.py, fromitive/partition-array-such-that-maximum-difference-is-k.py, fromitive/reduce-array-size-to-the-half.py, fromitive/softeer/CBTI.py, fromitive/softeer/gptnum.py, fromitive/softeer/wood-attack.py
=> [7주차 3회차] 포케

nak-honest/Baekjoon/PLATINUM/뱀(10875).py
https://www.acmicpc.net/problem/10875
진짜 난리도 아닌 문제네요 ㅋㅋㅋㅋㅋㅋㅋㅋㅋ
=> [7주차 3회차] 낙낙

slimsha2dy/2342.cpp
=> [7주차 1회차] 알파카

nak-honest/Baekjoon/GOLD/진우의_달_여행_(Large)(17485).py
https://www.acmicpc.net/problem/17485
=> [7주차 4회차] 낙낙

fromitive/binary-search.py, fromitive/koko-eating-bananas.py, fromitive/longest-subsequence-with-limited-sum.py, fromitive/search-a-2d-matrix.py, fromitive/search-insert-position.py, fromitive/softeer/yeah-but-how.py, fromitive/successful-pairs-of-spells-and-potions.py
=> [7주차 4회차] 포케

slimsha2dy/12738.cpp
뭔가 날먹 문제긴 한데 안풀려있는거 보기 싫어서 풀었슴다 ㅎㅎ
=> [7주차 2회차] 알파카

youngsu5582/week4/BJ_14395.kt, youngsu5582/week4/BJ_30701.kt
- 문제 링크 : https://www.acmicpc.net/problem/30701
- 문제 링크 : https://www.acmicpc.net/problem/14395
갈고리즘 문제 재밌네용 🙂
=> [7주차 2회차] 조이썬

nak-honest/Baekjoon/GOLD/암호_만들기(1759).py
https://www.acmicpc.net/problem/1759
=> [7주차 5회차] 낙낙

slimsha2dy/10814.cpp, slimsha2dy/1676.cpp
자소서 제출하고 급하게 풀어서 냈는데 버저비터 인정 되나요 ㅎㅎ
=> [7주차 4회차] 알파카

17404.cpp
=> [8주차 1회차] 알파카

slimsha2dy/2623.cpp
=> [8주차 2회차] 알파카

youngsu5582/week4/BJ_7453.kt
- 문제 링크 : https://www.acmicpc.net/problem/7453
AB + CD 인거 파악 못해서 1헤맴
`(abCount*cdCount).toLong()` 능지 이슈로 1헤맴...
=> [8주차 2회차] 조이썬

youngsu5582/week4/BJ_10799.kt, youngsu5582/week4/BJ_9466.kt
- 문제링크 : https://www.acmicpc.net/problem/10799
- 문제링크 : https://www.acmicpc.net/problem/9466
9466 번 문제 재밌네용. 풀어보시는거 추천합니다 🙂
=> [8주차 3회차] 조이썬

nak-honest/Baekjoon/GOLD/성냥개비(3687).py
https://www.acmicpc.net/problem/3687
=> [8주차 1회차] 낙낙

nak-honest/Baekjoon/GOLD/17404(RGB거리_2).py
https://www.acmicpc.net/problem/17404
=> [8주차 2회차] 낙낙

hyxrxn/c++/01074.cpp
=> [8주차 1회차] 아토

youngsu5582/week4/BJ_20207.kt
- 문제 링크 : https://www.acmicpc.net/problem/20207
재밌는 정렬 + 그리디 문제 한접시
=> [8주차 4회차] 조이썬

slimsha2dy/11866.cpp, slimsha2dy/17404.cpp, slimsha2dy/2839.cpp
=> [8주차 3회차] 알파카

fromitive/combination-sum.py, fromitive/min-cost-climbing-stairs.py, fromitive/numbers-with-same-consecutive-differences.py
=> [8주차 2회차] 포케

hyxrxn/c++/02146.cpp
=> [8주차 2회차] 아토

nak-honest/Baekjoon/GOLD/줄_세우기(2252).py
https://www.acmicpc.net/problem/2252
=> [8주차 3회차] 낙낙

youngsu5582/week4/BJ_6497.kt
- 문제 링크 : https://www.acmicpc.net/problem/6497
최소 신장 트리를 까먹었어용 🥲
=> [8주차 5회차] 조이썬

nak-honest/Baekjoon/GOLD/로봇_청소기(14503).py, nak-honest/Baekjoon/GOLD/최종_순위(3665).py
https://www.acmicpc.net/problem/3665
첨에 문제를 잘못 이해했네요 ㅠㅠ 문제를 더 꼼꼼히 봐야겠슴다..
=> [8주차 4회차] 낙낙

fromitive/house-robber.py, fromitive/longest-increasing-subsequence.py
=> [8주차 3회차] 포케

2042.cpp
=> [9주차 1회차] 알파카

Minjoo522/boj13235/Main.java, Minjoo522/boj18229/Main.java, Minjoo522/boj18406/Main.java, Minjoo522/boj2204/Main.java
=> [9주차 1회차] 리브

nak-honest/Baekjoon/GOLD/로봇_조종하기(2169).py
https://www.acmicpc.net/problem/2169
=> [9주차 1회차] 낙낙

fromitive/climbing-stairs.py, fromitive/solving-questions-with-brainpower.py
햇갈리는 DP 기초문제를 풀어봤습니다~
선택할 수 있는 케이스들을 잘 고려하면 잘 풀 수 있을듯!!
=> [9주차 1회차] 포케

slimsha2dy/11505.cpp
세그트리 기본문제 미는중..
기본문제인데 골1 너무 달콤해
=> [9주차 2회차] 알파카

youngsu5582/week5/PROGRAMMERS_43163.kt, youngsu5582/week5/PROGRAMMERS_92341.kt
- 문제 링크 : https://school.programmers.co.kr/learn/courses/30/lessons/92341
- 문제 링크 : https://school.programmers.co.kr/learn/courses/30/lessons/43163
프로그래머스 재활훈련
=> [9주차 2회차] 조희선

nak-honest/Baekjoon/GOLD/줄세우기(2631).py
https://www.acmicpc.net/problem/2631
제가 어제 풀어놓고 PR을 까먹었네요!!
일주일간 해외 봉사 중이라 정신이 많이 없습니다 ㅠㅠ
=> [9주차 2회차] 낙낙

youngsu5582/week5/BJ_13334.kt, youngsu5582/week5/BJ_15927.kt
- 문제 링크 : https://www.acmicpc.net/problem/13334
- 문제 링크 : https://www.acmicpc.net/problem/15927
절대 회문을 무시하지마.
=> [9주차 3회차] 조희선

fromitive/best-time-to-buy-and-sell-stock-iv.py, fromitive/longest-common-subsequence.py
다이나믹 프로그래밍은 의사 결정 요소들을 잘 정의해야겠어요.
=> [9주차 3회차] 포케

fromitive/maximum-value-of-k-coins-from-piles.py
오늘은 가볍게 `dp` 하나 풀었어요
bottom-up으로 변환하는걸 좀 연습해야겠네요
=> [9주차 5회차] 포케

slimsha2dy/2357.cpp
=> [9주차 4회차] 알파카

nak-honest/Baekjoon/GOLD/돌_그룹(12886).py
https://www.acmicpc.net/problem/12886
=> [9주차 5회차] 낙낙

slimsha2dy/18436.cpp
=> [9주차 5회차] 알파카

fromitive/best-time-to-buy-and-sell-stock-transaction-fee.py, fromitive/best-time-to-buy-and-sell-stock-with-cooldown.py
=> [10주차 1회차] 포케

youngsu5582/week6/BJ_1339.kt, youngsu5582/week6/BJ_30644.java, youngsu5582/week6/BJ_30648.java
- 문제링크 : https://www.acmicpc.net/problem/1339
- 문제링크 : https://www.acmicpc.net/problem/30644
- 문제링크 : https://www.acmicpc.net/problem/30648
1339 진짜 무식하게 풀리는데, 이게 맞나? 싶긴 하네용
=> [10주차 2회차] 이영수

youngsu5582/week6/BJ_30508.java, youngsu5582/week6/BJ_30618.java
- 문제링크 : https://www.acmicpc.net/problem/30508
- 문제링크 : https://www.acmicpc.net/problem/30618
30508 온몸비틀기로 풀었는데 저게 맞나 싶긴 하네용 쩝
=> [10주차 3회차] 조희선

Dobby-Kim/week10/1st/1259.java, Dobby-Kim/week10/1st/1978.java, Dobby-Kim/week10/1st/2798.java, Dobby-Kim/week10/1st/4153.java
그 동안 너무 나태했습니다.. 브론즈 문제로 재활치료부터 다시 시작하겠습니다.. 
| 문제 번호 | 문제 제목 |
|----------|----------|
| 2798     | [블랙잭](https://www.acmicpc.net/problem/2798) |
| 4153     | [직각삼각형](https://www.acmicpc.net/problem/4153) |
| 1978     | [소수 찾기](https://www.acmicpc.net/problem/1978) |
| 1259     | [팰린드롬수](https://www.acmicpc.net/problem/1259) |
=> [10주차 1회차] 도비

slimsha2dy/33542.cpp
=> [10주차 2회차] 알파카

slimsha2dy/14427.cpp
=> [10주차 3회차] 알파카

fromitive/minimum-falling-path-sum.py, fromitive/minimum-path-sum.py, fromitive/unique-paths-ii.py, fromitive/unique-paths.py
=> [10주차 2회차] 포케

hyxrxn/c++/programmers/017684.cpp, hyxrxn/c++/programmers/017687.cpp
- 017687 [3차] n진수 게임 (프로그래머스 레벨 2)
- 017684 [3차] 압축 (프로그래머스 레벨 2)
=> [10주차 2회차] 아토

nak-honest/Baekjoon/GOLD/슬슬_가지를_먹지_않으면_죽는다(27945).py
https://www.acmicpc.net/problem/27945
나도 가지 먹을래 내놔
=> [10주차 4회차] 낙낙

youngsu5582/week6/BJ_30504.java, youngsu5582/week6/LeetCode_167.kt, youngsu5582/week6/LeetCode_3.kt, youngsu5582/week6/LeetCode_55.kt
=> [10주차 4회차] 조희선

ehBeak/src/week10/Boj13549.java
[https://www.acmicpc.net/problem/13549](https://www.acmicpc.net/problem/13549)
=> [10주차 3회차] 배키

nak-honest/Baekjoon/GOLD/사다리_조작(15684).py
https://www.acmicpc.net/problem/15684
사다리 미션이 생각나는 문제네요!
`Line` 객체 만들어서 객체지향적으로 풀고싶은 욕구가,,,
=> [10주차 5회차] 낙낙

slimsha2dy/17835.cpp, slimsha2dy/30470.cpp, slimsha2dy/30985.cpp
=> [10주차 5회차] 알파카

slimsha2dy/11003.cpp, slimsha2dy/11003_2.cpp
입력 범위와 시간 제한을 보면 NlogL로 풀릴 것 같아 set으로 하니까 안되네요.
근데 우선순위 큐로 하면 풀립니다.
근데 우선순위 큐로 푸는 경우 플레 문제는 전혀 아닌 것 같아 찾아보니 O(N)을 의도한 단조 큐 문제였네요
=> [11주차 1회차] 알파카

nak-honest/Baekjoon/GOLD/A를_B로(13019).py
https://www.acmicpc.net/problem/13019
그리디 열심히 푸는 중입네다
다른 유형에 비해 그리디를 너무 안푼거 같아요 ㅎㅎ
=> [11주차 1회차] 낙낙

youngsu5582/week6/BJ_1368.kt, youngsu5582/week6/BJ_30644.java, youngsu5582/week7/BJ_10773.kt, youngsu5582/week7/BJ_14602.kt, youngsu5582/week7/BJ_29717.kt, youngsu5582/week7/BJ_29728.kt
- 문제링크
https://www.acmicpc.net/problem/10773
https://www.acmicpc.net/problem/14602
https://www.acmicpc.net/problem/29717
https://www.acmicpc.net/problem/29728
다시 난이도를 올려봐야겠습니다. 🫡
=> [11주차 1회차] 조희선

helenason/programmers/P133500.java
=> [11주차 1회차] 에버

slimsha2dy/24508.cpp
=> [11주차 2회차] 알파카

helenason/programmers/P132266.java
=> [11주차 2회차] 에버

hyxrxn/c++/programmers/012927.cpp, hyxrxn/c++/programmers/043105.cpp, hyxrxn/c++/programmers/043162.cpp
- 043105 정수 삼각형 (프로그래머스 레벨 3)
- 043162 네트워크 (프로그래머스 레벨 3)
- 012927 야근 지수 (프로그래머스 레벨 3)
=> [11주차 2회차] 아토

shin-jisong/week9/day2/boj10814.py, shin-jisong/week9/day2/boj11650.py
실수로 메인에 바로 커밋했습니다 😖
정정 커밋 올렸어요 죄삼다..........
=> [11주차 2회차] 시소

Minjoo522/boj14405/Main.java, Minjoo522/boj25496/Main.java
=> [11주차 2회차] 리브

slimsha2dy/30191.cpp
=> [11주차 3회차] 알파카

hyxrxn/c++/programmers/012938.cpp, hyxrxn/c++/programmers/042898.cpp
- 042898 등굣길 (프로그래머스 레벨 3)
- 012938 최고의 집합 (프로그래머스 레벨 3)
=> [11주차 3회차] 아토

helenason/programmers/P12927.java
최댓값 최솟값 찾기만을 위해 정렬 사용하는 것은 시간 낭비
- 우선순위큐를 적절히 활용하자
- `Comparator.reverseOrder()` -> 이 친구 자꾸 까먹음 ㅠㅠ
=> [11주차 3회차] 에버

Minjoo522/boj24508/Main.java
=> [11주차 3회차] 리브

slimsha2dy/17831.cpp
=> [11주차 5회차] 알파카

fromitive/find-pivot-index.py, fromitive/get-equal-substrings-within-budget.py, fromitive/maximum-number-of-vowels-in-a-substring-of-given-length.py, fromitive/minimum-common-value.py, fromitive/range-sum-query-immutable.py
=> [12주차 1회차] 포케

nak-honest/Baekjoon/GOLD/사전_순_최대_공통_부분_수열(30805).py
https://www.acmicpc.net/problem/30805
저번주엔 프로그래머스 문제를 많이 풀었는데 깃헙에 올리지는 못했네요 ㅎㅎ
이번주부터 다시 백준 달려보겠심다!
=> [12주차 1회차] 낙낙

Minjoo522/boj24431/Main.java, Minjoo522/boj29808/Main.java
=> [12주차 1회차] 리브

nak-honest/Baekjoon/GOLD/ACM_Craft(1005).py
https://www.acmicpc.net/problem/1005
=> [12주차 2회차] 낙낙

hyxrxn/c++/programmers/012987.cpp, hyxrxn/c++/programmers/042884.cpp
- 012987 숫자 게임 (프로그래머스 레벨 3)
- 042884 단속카메라 (프로그래머스 레벨 3)
=> [12주차 1회차] 아토

nak-honest/Baekjoon/GOLD/텀_프로젝트(9466).py
https://www.acmicpc.net/problem/9466
=> [12주차 4회차] 낙낙

nak-honest/Baekjoon/GOLD/합이_0인_네_정수(7453).py
https://www.acmicpc.net/problem/7453
오우 파이썬 느려서 좀 빡세네요
C++은 O(n^2 * log n) 이 된다던데
파이썬은 pypy3로 O(n^2) 만 되네요
=> [12주차 5회차] 낙낙

hyxrxn/c++/programmers/012979.cpp, hyxrxn/c++/programmers/042579.cpp, hyxrxn/c++/programmers/067258.cpp
=> [12주차 3회차] 아토

hyxrxn/c++/programmers/012979.cpp, hyxrxn/c++/programmers/042579.cpp
- 012979 기지국 설치 (프로그래머스 레벨 3)
- 042579 베스트앨범 (프로그래머스 레벨 3)
=> [12주차 2회차] 아토

nak-honest/Baekjoon/GOLD/2048_(Easy)(12100).py
https://www.acmicpc.net/problem/12100
어제랑 같은 티어의 구현 문제이지만, 더 쉬운 느낌이네요!!
=> [13주차 2회차] 낙낙

slimsha2dy/1797.cpp
=> [13주차 1회차] 알파카

nak-honest/Baekjoon/GOLD/카드_정렬하기(1715).py
https://www.acmicpc.net/problem/1715
=> [13주차 3회차] 낙낙

nak-honest/Baekjoon/GOLD/저울(2437).py
https://www.acmicpc.net/problem/2437
=> [13주차 4회차] 낙낙

nak-honest/Baekjoon/GOLD/욕심쟁이_판다(1937).py
https://www.acmicpc.net/problem/1937
=> [13주차 5회차] 낙낙

hyxrxn/c++/programmers/067259.cpp
=> [13주차 3회차] 아토

hyxrxn/c++/programmers/012904.cpp
- 012904 가장 긴 팰린드롬 (프로그래머스 레벨 3)
=> [14주차 1회차] 아토

nak-honest/Baekjoon/GOLD/수_나누기_게임(27172).py
https://www.acmicpc.net/problem/27172
=> [14주차 1회차] 낙낙

fromitive/binary-subarrays-with-sum.py, fromitive/maximum-erasure-value.py
=> [14주차 1회차] 포케

slimsha2dy/16946.cpp
=> [14주차 1회차] 알파카

hyxrxn/c++/programmers/042627.cpp
- 042627 디스크 컨트롤러 (프로그래머스 레벨 3)
=> [14주차 2회차] 아토

nak-honest/Baekjoon/GOLD/두_배열의_합(2143).py
https://www.acmicpc.net/problem/2143
=> [14주차 2회차] 낙낙

nak-honest/Baekjoon/GOLD/공항(10775).py
https://www.acmicpc.net/problem/10775
매개 변수 탐색으로도 풀리는군요!
다른 사람들하곤 좀 다르게 푼거 같슴다 ㅎㅎ
=> [14주차 5회차] 낙낙

hyxrxn/c++/programmers/077486.cpp
- 077486 다단계 칫솔 판매 (프로그래머스 레벨 3)
=> [14주차 3회차] 아토

nak-honest/Baekjoon/GOLD/1의_개수_세기(9527).py
https://www.acmicpc.net/problem/9527
=> [15주차 1회차] 낙낙

jhon3242/baekjoon/1904.java, jhon3242/baekjoon/24416.java, jhon3242/baekjoon/9184.java
=> [15주차 2~3회차] 타칸 

hyxrxn/c++/programmers/012907.cpp, hyxrxn/c++/programmers/068646.cpp
- 012907 거스름돈 (프로그래머스 레벨 3)
- 068646 풍선 터트리기 (프로그래머스 레벨 3)
=> [15주차 1회차] 아토

jhon3242/baekjoon/1149.java, jhon3242/baekjoon/1921.java, jhon3242/baekjoon/9461.java
=> [15주차 4회차] 타칸

hyxrxn/c++/programmers/092344.cpp
- 092344 파괴되지 않은 건물 (프로그래머스 레벨 3)
누적합까진 생각했는데...
어렵네요
=> [15주차 2회차] 아토

hyxrxn/c++/baekjoon/32983.cpp
=> [15주차 3회차] 아토

jhon3242/baekjoon/1932.java, jhon3242/baekjoon/2579.java
=>  [15주차 5회차] 타칸

nak-honest/Baekjoon/GOLD/1학년(5557).py
https://www.acmicpc.net/problem/5557
=> [16주차 1회차] 낙낙

fromitive/custom-sort-string.py, fromitive/delete-the-middle-node-of-a-linked-list.py, fromitive/determine-if-two-strings-are-close.py, fromitive/permutation-in-string.py, fromitive/word-pattern.py
=> [16주차 1회차] 포케

nak-honest/Baekjoon/GOLD/가운데를_말해요(1655).py
https://www.acmicpc.net/problem/1655
재밌는 문제네요!
=> [16주차 2회차] 낙낙

jhon3242/baekjoon/12865-2th.java, jhon3242/baekjoon/1463-2th.java, jhon3242/baekjoon/1904-2th.java, jhon3242/baekjoon/2565-2th.java, jhon3242/baekjoon/2579-2th.java, jhon3242/baekjoon/9251-2th.java
=> [18주차 1~5회차] 타칸

jhon3242/baekjoon/3665-2th.java
=> [25주차 2회차] 타칸 

nak-honest/Baekjoon/GOLD/1261(알고스팟).py
오랜만입니다 여러분!
오늘부터 다시 알고리즘 시작합니다 ㅎ..
이 어려운 취업 시기 끝까지 버텨 보시자구요!!!
=> [32주차 1회차] 낙낙
